journals:
  - neurolibre/neurolibre-reviews:
      editor_team_id: 3408147
      eics:
        - emdupre
      eic_team_name: neurolibre/editors
      papers_repo: neurolibre/neurolibre-papers
      reviewers: https://tinyurl.com/y22xx6ux
      reviewers_signup: ''
      site_host: https://neurolibre.herokuapp.com
      doi_prefix: ""
      journal_alias: NeuroLibre
      journal_launch_date: ''
      journal_issn: ''
      site_name: NeuroLibre
      donate_url: ''
      site_api_key: <%= ENV['JOSS_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>

  - openjournals/joss-reviews-testing:
      editor_team_id: 3408147
      eics:
        - emdupre
      eic_team_name: neurolibre/editors
      papers_repo: neurolibre/neurolibre-papers
      reviewers: https://tinyurl.com/y22xx6ux
      reviewers_signup: ''
      site_host: https://neurolibre.herokuapp.com
      doi_prefix: ""
      journal_alias: NeuroLibre
      journal_launch_date: ''
      journal_issn: ''
      site_name: NeuroLibre
      donate_url: ''
      site_api_key:
      crossref_username:
      crossref_password:
      twitter_consumer_key:
      twitter_consumer_secret:
      twitter_access_token:
      twitter_access_token_secret:
